version: "3.9"

services:
  makis:
    container_name: makis
    image: nachovbordera/makis:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}

  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - makisdata:/var/lib/postgresql/data

volumes:
  makisdata: {}
